# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build ImageShaper

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: "Install .NET Framework 3.5"
      run: Enable-WindowsOptionalFeature -Online -FeatureName "Netfx3" -All
    - name: "Build"
      run: C:\Windows\Microsoft.NET\Framework\v3.5\MSBuild.exe ImageShaper.sln
    - name: Upload ImageShaper Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ImageShaper_CHS
        path: bin/Release/
    - name: Download a single artifact
      uses: actions/download-artifact@v4
    - name: Release ImageShaper
      if: github.event_name != 'pull_request'
      uses: marvinpinto/action-automatic-releases@master
      with:
        title: "ImageShaper_CHS"
        automatic_release_tag: "CHS"
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        files: ImageShaper_CHS.zip
        prerelease: false
